ARG TAG=stream9
FROM quay.io/centos/centos:${TAG}
ENV LC_CTYPE=C.UTF-8

RUN cat /etc/os-release

RUN dnf -y update && \
    dnf -y install \
    make \
    python3 \
    python3-pip \
    python3-gobject-base \
    dbus-daemon \
    && dnf clean all

COPY requirements.txt .

RUN pip3 install -U pip && \
    pip3 install -U -r requirements.txt
