FROM fedora:rawhide
ENV LANG C.utf8

RUN dnf -y install \
    make \
    python3 \
    python3-pip \
    python3-gobject-base \
    python3-sphinx \
    dbus-daemon

RUN pip3 install \
    sphinx_rtd_theme \
    coverage \
    pylint
