ARG TAG=latest
FROM debian:${TAG}
ENV LC_CTYPE=C.UTF-8

RUN cat /etc/os-release

RUN apt-get update && \
    apt-get install -y \
    make \
    python3 \
    python3-pip \
    python3-venv \
    python3-gi \
    dbus-daemon \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip3 install -U pip && \
    pip3 install -U -r requirements.txt
