ARG TAG=rawhide
FROM registry.fedoraproject.org/fedora:${TAG}
ENV LANG=C.utf8

RUN cat /etc/os-release

RUN dnf -y update && \
    dnf -y install \
    gcc \
    make \
    python3 \
    python3-pip \
    python3-wheel \
    python3-gobject-base \
    dbus-daemon \
    && dnf clean all

RUN pip3 install \
    sphinx \
    sphinx_rtd_theme \
    sphinxcontrib-apidoc \
    coverage \
    pylint
