ARG TAG=latest
FROM python:${TAG}
ENV LANG=C.utf8

RUN cat /etc/os-release

RUN apt-get update && \
    apt-get install -y \
    make \
    gcc \
    pkg-config \
    python3-dev \
    libgirepository1.0-dev \
    dbus-daemon \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
    PyGObject \
    sphinx \
    sphinx_rtd_theme \
    sphinxcontrib-apidoc \
    coverage \
    pylint
