FROM quay.io/centos/centos:stream8
ENV LANG=C.utf8

# The pylintrc file is no longer compatible with older pylint.
ENV CHECK_ARGS="--disable=no-self-use,bad-option-value"

RUN yum -y update; \
    yum -y install \
    make \
    python3 \
    python3-pip \
    python3-gobject-base \
    dbus-daemon; \
    yum clean all

RUN pip3 install \
    sphinx \
    sphinx_rtd_theme \
    coverage \
    pylint
